version: '3'

services:
    php:
        container_name: paroki.php
        build:
            context: ./etc/docker/php
        depends_on:
          - db
        volumes:
            - ./:/app:rw
            - /app/var
            - /app/public/bundles
        environment:
            - APP_DEBUG = ${APP_DEBUG}

    nginx:
        container_name: paroki.nginx
        build:
            context: ./etc/docker/nginx
        depends_on:
            - php
        ports:
            - "80:80"
        volumes:
            - ./:/app

    db:
        # In production, you may want to use a managed database service
        container_name: paroki.db
        build:
            context: ./etc/docker/postgres
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            # You should definitely change the password in production
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - ./var/postgres/data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
