<?php

return array(
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => array('all' => true),
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => array('all' => true),
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => array('all' => true),
    Symfony\Bundle\MonologBundle\MonologBundle::class => array('all' => true),
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => array('all' => true),
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => array('all' => true),
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => array('all' => true),
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => array('dev' => true, 'test' => true),
    Symfony\Bundle\TwigBundle\TwigBundle::class => array('all' => true),
    Symfony\Bundle\DebugBundle\DebugBundle::class => array('dev' => true, 'test' => true),
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => array('all' => true),
    Symfony\Bundle\MakerBundle\MakerBundle::class => array('dev' => true),
    Nelmio\CorsBundle\NelmioCorsBundle::class => array('all' => true),
    ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle::class => array('all' => true),
    Paroki\Frontend\ParokiFrontendBundle::class => array('all' => true),
    Paroki\Resource\ParokiResourceBundle::class => array('all' => true),
    Paroki\Security\ParokiSecurityBundle::class => array('all' => true),
    Hautelook\AliceBundle\HautelookAliceBundle::class => array('all' => true),
    Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle::class => array('all' => true),
    Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => array('all' => true),
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => array('all' => true),
    FOS\UserBundle\FOSUserBundle::class => array('all' => true),
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => array('all' => true),
    Lexik\Bundle\MaintenanceBundle\LexikMaintenanceBundle::class => array('all' => true),
);
