lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/%env(resolve:JWT_PRIVATE_KEY_PATH)%'
    public_key_path:  '%kernel.project_dir%/%env(resolve:JWT_PUBLIC_KEY_PATH)%'
    pass_phrase:      '%env(resolve:JWT_PASSPHRASE)%'

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Paroki\Resource\Entity\User
    from_email:
        address: "%env(MAILER_USER)%"
        sender_name: "%env(MAILER_USER)%"
    use_listener: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ADMIN_PAROKI:    USER
        ADMIN:           ADMIN_PAROKI
        SUPER_ADMIN:     ADMIN

    providers:
        in_memory: { memory: ~ }
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            json_login:
                check_path: /login_check
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|bundles)/
            security: false
        main:
            pattern:      ^/api
            provider:     fos_userbundle
            stateless:    true
            anonymous:    ~
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
