api_platform:
    #name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    version: 1.0.0
    enable_fos_user: true
    swagger:
        api_keys:
            apiKey:
                name: 'Authorization'
                type: 'header'
    collection:
        pagination:
            items_per_page: 5

